### ISSUE TITLE
Failing tests in zgo/zgo_test.go:13

### ISSUE THREAD

**Issue by melledouwsma** [arp242/zstd#1]
Hi,

We're trying to compile this module and I'm having some trouble getting the tests to pass. The tests keep failing on [zgo/zgo_test.go:13](https://github.com/zgoat/zstd/blob/a4927f23388f32342e53b0ac0cedf7ef4b452047/zgo/zgo_test.go#L13). However, I am not completely sure of what is being tested here. I seems that all cases where the tests are not run from `/home/martin/code/zstd` will fail. Is it possible to change that, or to point me in the direction of how I can write a Pull Request to resolve this issue. Thank you!

```
zgo.at/zstd/zbool
PASS
ok  	zgo.at/zstd/zbool	0.003s
zgo.at/zstd/zbyte
PASS
ok  	zgo.at/zstd/zbyte	0.002s
zgo.at/zstd/zcrypto
PASS
ok  	zgo.at/zstd/zcrypto	0.002s
zgo.at/zstd/zdebug
	zdebug_test.go:10   zgo.at/zstd/zdebug.TestPrintStack.func1
	zdebug_test.go:11   zgo.at/zstd/zdebug.TestPrintStack
zdebug_test.go:16
zdebug_test.go:19
testing.go:1193
PASS
ok  	zgo.at/zstd/zdebug	0.002s
zgo.at/zstd/zfilepath
PASS
ok  	zgo.at/zstd/zfilepath	0.001s
zgo.at/zstd/zfloat
PASS
ok  	zgo.at/zstd/zfloat	0.002s
zgo.at/zstd/zfmt
PASS
ok  	zgo.at/zstd/zfmt	0.002s
zgo.at/zstd/zfs
PASS
ok  	zgo.at/zstd/zfs	0.002s
zgo.at/zstd/zgo
--- FAIL: TestModuleRoot (0.00s)
    zgo_test.go:13: /builddir/build/BUILD/zstd-a4927f23388f32342e53b0ac0cedf7ef4b452047/_build/src/zgo.at/zstd
FAIL
exit status 1
FAIL	zgo.at/zstd/zgo	0.002s
```

**Comment by arp242** [comment]
This test assume my directory layout on my laptop:

https://github.com/zgoat/zstd/blob/a4927f23388f32342e53b0ac0cedf7ef4b452047/zgo/zgo_test.go#L11-L14

That's probably something different for you, and almost everyone else on the planet for that matter 🙃

Since few people actually use this library I figured it would be fine like this. Should really compare to `os.Getwd()` value, but that was more work.

I'll be happy to merge a patch to fix it.

**Comment by arp242** [comment]
Although, the problem is that any test which tests this properly essentially needs to copy the `ModuleRoot()` implementation.

Could do `strings.HasPrefix(os.Getwd(), ModuleRoot())`, but that will also pass if it ends up in the wrong directory.

Maybe run `go list` and compare to the output of that?

**Comment by arp242** [comment]
```
[~c/zstd/zgo](master)% go list -m -f '{{.GoMod}}'
/home/martin/code/zstd/go.mod
```

Sorry for multiple messages, I'm super tired 😅
